services:
  meterman:
    image: aamcrae/meterman:latest
    container_name: meterman
    restart: always
    # User 'meter' uid and gid
    user: "${METERUID}:${METERGID}"
    volumes:
      - "/var/cache/mman:/data"
      - "./config.yml:/config"
    ports:
      - "8080:8080"
    environment:
      - TZ=Australia/Sydney
